name: 'GitVersion Action'
description: 'This GitHub Action extracts version information using GitVersion.'

inputs:
  useGitVersionDefaultConfig:
    description: 'Whether to use the default GitVersion configuration'
    required: false
    default: 'true'

  gitVersionConfigFilePath:
    description: 'Path to a custom GitVersion configuration file'
    required: false
    default: 'gitversion.yml'
  
  useCliffDefaultConfig:
    description: 'Whether to use the default git-cliff configuration'
    required: false
    default: 'true'

  cliffConfigFilePath:
    description: 'Path to a custom git-cliff configuration file'
    required: false
    default: 'cliff.toml'

  isTerraformModule:
    description: 'Whether the repository is a Terraform module'
    required: false
    default: 'false'

outputs:
  majorVersion:
    description: 'Major version number'
    value: ${{ steps.gitversion.outputs.major }}

  minorVersion:
    description: 'Minor version number'
    value: ${{ steps.gitversion.outputs.minor }}

  patchVersion:
    description: 'Patch version number'
    value: ${{ steps.gitversion.outputs.patch }}

  majorMinorVersion:
    description: 'Major.Minor version'
    value: ${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}
  
  majorMinorPatchVersion:
    description: 'Major.Minor.Patch version'
    value: ${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}

runs:
  using: 'composite'
  steps:
    - name: Install Terraform
      if: ${{ inputs.isTerraformModule == 'true' }}
      uses: hashicorp/setup-terraform@v3

    - name: Terraform fmt
      if: ${{ inputs.isTerraformModule == 'true' }}
      shell: bash
      run: terraform fmt -check
      continue-on-error: false

    - name: Create default GitVersion config
      if: ${{ inputs.useGitVersionDefaultConfig == 'true' }}
      shell: bash
      run: |
        echo "==> Creating default GitVersion configuration file (gitversion.yml)..."
        cat > gitversion.yml << 'EOF'
        workflow: GitHubFlow/v1
        tag-prefix: '[vV]'
        major-version-bump-message: '(BREAKING CHANGE|^.+!:)'
        minor-version-bump-message: '^feat(\([^)]+\))?:\s'
        patch-version-bump-message: '^(fix|perf|refactor|revert|chore|docs|style|test|ci)(\([^)]+\))?:\s'
        #patch-version-bump-message: '^(fix|perf|refactor|revert)(\([^)]+\))?:\s'
        #no-bump-message: '^(chore|docs|style|test|ci)(\([^)]+\))?:\s'
        commit-message-incrementing: Enabled
        strategies:
          - MergeMessage
          - TaggedCommit
          - TrackReleaseBranches
          - VersionInBranchName
        branches:
          main:
            mode: ContinuousDeployment
            increment: Patch
            regex: ^master$|^main$
            is-main-branch: true
          release:
            mode: ContinuousDeployment
            increment: Minor
            regex: ^release/(?<BranchName>[0-9]+\.[0-9]+\.[0-9]+)$
            is-release-branch: true
          develop:
            mode: ContinuousDelivery
            increment: Patch
            regex: ^dev(elop)?(ment)?$
        commit-date-format: ddMMyyyy
        assembly-versioning-scheme: MajorMinorPatch
        assembly-informational-format: '{SemVer}'
        EOF
        echo "Default gitversion.yml created."

    - name: Create default cliff.toml config
      if: ${{ inputs.useCliffDefaultConfig == 'true' }}
      shell: bash
      run: |
        echo "==> Creating default Cliff configuration file (cliff.toml)..."
        cat > cliff.toml << 'EOF'
        [changelog]
        # Global template
        header = """# Change Log

        All notable changes to this project will be documented in this file.

        """

        # Template for each version
        body = """
        ## [CHANGEME](${{ github.server_url }}/${{ github.repository }}/compare/{{ previous.version }}...CHANGEME) ({{ now() | date(format="%Y-%m-%d") }})

        {% for commit in commits %}- {{ commit.message | split(pat="\n") | first | upper_first }}\n{% endfor %}

        """

        [git]
        tag_filter_pattern = "^v[0-9]{1,}\\.[0-9]{1,}\\.[0-9]{1,}$"

        footer = ""
        trim = true

        EOF
        echo "Default cliff.toml created."

    - name: Set up git-cliff
      uses: kenji-miyake/setup-git-cliff@v1
      
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v4
      with:
        versionSpec: '6.4.x'

    - name: Execute GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v4
      with:
        configFilePath: ${{ inputs.gitVersionConfigFilePath }}

    - name: Configure Git
      shell: bash
      run: |
        echo "==> Configuring Git user..."
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Push Major Version Tag
      shell: bash
      run: |
        echo "==> Preparing to push Major version tag: v${{ steps.gitversion.outputs.major }}"
        
        echo "Deleting local and remote tag if exists..."
        git tag -d "v${{ steps.gitversion.outputs.major }}" || true
        git push origin ":refs/tags/v${{ steps.gitversion.outputs.major }}" || true

        if [ "${{ inputs.isTerraformModule }}" = "true" ]; then
          echo "Updating Terraform files with new major version..."
          sed -i "s/\(\"technical:module:version\"\).*/\1 : \"${{ steps.gitversion.outputs.major }}\"/" 01-locals.tf
          sed -i "s/\(terraform-aws-.*?ref=\).*/\1v${{ steps.gitversion.outputs.major }}\"/" README.md
          sed -i "s/\(terraform-aws-.*?ref=\).*/\1v${{ steps.gitversion.outputs.major }}\"/" .terraform-docs.yml
        fi

        echo "Generating changelog with git-cliff..."
        git cliff --config ${{ inputs.cliffConfigFilePath }} -u --prepend CHANGELOG.md
        sed -i "s/CHANGEME/${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}/g" CHANGELOG.md

        echo "Staging and committing changes (if any)..."
        git add 01-locals.tf README.md .terraform-docs.yml CHANGELOG.md || true
        git commit -m "chore: bump module version to v${{ steps.gitversion.outputs.major }}" || echo "No changes to commit."

        echo "Tagging and pushing v${{ steps.gitversion.outputs.major }}..."
        git tag "v${{ steps.gitversion.outputs.major }}"
        git push origin "v${{ steps.gitversion.outputs.major }}"

    - name: Push Major.Minor Version Tag
      shell: bash
      run: |
        echo "==> Preparing to push Major.Minor version tag: v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}"

        echo "Deleting local and remote tag if exists..."
        git tag -d "v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}" || true
        git push origin ":refs/tags/v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}" || true

        if [ "${{ inputs.isTerraformModule }}" = "true" ]; then
          echo "Updating Terraform files with new major.minor version..."
          sed -i "s/\(\"technical:module:version\"\).*/\1 : \"${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}\"/" 01-locals.tf
          sed -i "s/\(terraform-aws-.*?ref=\).*/\1v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}\"/" README.md
          sed -i "s/\(terraform-aws-.*?ref=\).*/\1v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}\"/" .terraform-docs.yml
        fi

        echo "Staging and committing changes (if any)..."
        git add 01-locals.tf README.md .terraform-docs.yml || true
        git commit -m "chore: bump module version to v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}" || echo "No changes to commit."

        echo "Tagging and pushing v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}..."
        git tag "v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}"
        git push origin "v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}"
    
    - name: Push Major.Minor.Patch Version Tag
      shell: bash
      run: |
        echo "==> Preparing to push Major.Minor.Patch version tag: v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}"

        if [ "${{ inputs.isTerraformModule }}" = "true" ]; then
          echo "Updating Terraform files with new major.minor.patch version..."
          sed -i "s/\(\"technical:module:version\"\).*/\1 : \"${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}\"/" 01-locals.tf
          sed -i "s/\(terraform-aws-.*?ref=\).*/\1v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}\"/" README.md
          sed -i "s/\(terraform-aws-.*?ref=\).*/\1v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}\"/" .terraform-docs.yml
        fi

        echo "Staging and committing changes (if any)..."
        git add 01-locals.tf README.md .terraform-docs.yml|| true
        git commit -m "chore: bump module version to v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}" || echo "No changes to commit."

        echo "Tagging and pushing v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}..."
        git tag "v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}"
        git push origin "v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}"

    - name: Push changes in current branch
      shell: bash
      run: |
        echo "Pushing changes to origin branch $CURRENT_BRANCH..."
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        git push origin "$CURRENT_BRANCH"

    - name: Set outputs
      shell: bash
      run: |
        echo "==> Setting outputs for next steps..."
        echo "gitversion-fullsemver=${{ steps.gitversion.outputs.fullSemVer }}" >> $GITHUB_OUTPUT
        echo "gitversion-sha=${{ steps.gitversion.outputs.sha }}" >> $GITHUB_OUTPUT
        echo "Outputs set:"
        echo "  - fullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
        echo "  - sha: ${{ steps.gitversion.outputs.sha }}"
