name: 'GitVersion Action'
description: 'This GitHub Action extracts version information using GitVersion.'

inputs:
  useDefaultConfig:
    description: 'Whether to use the default GitVersion configuration'
    required: false
    default: 'true'

  configFilePath:
    description: 'Path to a custom GitVersion configuration file'
    required: false
    default: 'gitversion.yml'

  isTerraformModule:
    description: 'Whether the repository is a Terraform module'
    required: false
    default: 'false'

  pushMajorVersionTag:
    description: 'Whether to push a Major version tag to the repository'
    required: false
    default: 'false'

  pushMajorMinorVersionTag:
    description: 'Whether to push a Major.Minor version tag to the repository'
    required: false
    default: 'false'

  pushMajorMinorPatchVersionTag:
    description: 'Whether to push a Major.Minor.Patch version tag to the repository'
    required: false
    default: 'false'

outputs:
  majorVersion:
    description: 'Major version number'
    value: ${{ steps.gitversion.outputs.major }}

  minorVersion:
    description: 'Minor version number'
    value: ${{ steps.gitversion.outputs.minor }}

  patchVersion:
    description: 'Patch version number'
    value: ${{ steps.gitversion.outputs.patch }}

  majorMinorVersion:
    description: 'Major.Minor version'
    value: ${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}
  
  majorMinorPatchVersion:
    description: 'Major.Minor.Patch version'
    value: ${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}

runs:
  using: 'composite'
  steps:
    - name: Create default GitVersion config
      if: ${{ inputs.useDefaultConfig == 'true' }}
      shell: bash
      run: |
            cat > gitversion.yml << 'EOF'
            workflow: GitHubFlow/v1
            
            tag-prefix: '[vV]'
            
            major-version-bump-message: '(BREAKING CHANGE|^.+!:)'
            minor-version-bump-message: '^feat(\([^)]+\))?:\s'
            patch-version-bump-message: '^(fix|perf|refactor|revert)(\([^)]+\))?:\s'
            no-bump-message: '^(chore|docs|style|test|ci)(\([^)]+\))?:\s'
            
            commit-message-incrementing: Enabled
            
            strategies:
              - MergeMessage
              - TaggedCommit
              - TrackReleaseBranches
              - VersionInBranchName
            
            branches:
              main:
                mode: ContinuousDeployment
                increment: Patch
                regex: ^master$|^main$
                is-main-branch: true
                
              release:
                mode: ContinuousDeployment
                increment: None
                regex: ^release/(?<BranchName>[0-9]+\.[0-9]+\.[0-9]+)$
                is-release-branch: true
              
              develop:
                mode: ContinuousDelivery
                increment: Minor
                regex: ^dev(elop)?(ment)?$

            commit-date-format: ddMMyyyy

            assembly-versioning-scheme: MajorMinorPatch
            assembly-informational-format: '{SemVer}'
            EOF

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v4
      with:
        versionSpec: '6.4.x'

    - name: Execute GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v4
      with:
        configFilePath: ${{ inputs.configFilePath }}

    - name: Push Major Version Tag
      if: ${{ inputs.pushMajorVersionTag == 'true' }}
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "mbasri.dev@outlook.com"

        git tag -d "v${{ steps.gitversion.outputs.major }}" || true
        git push origin ":refs/tags/v${{ steps.gitversion.outputs.major }}" || true

        git checkout -b tmp-release-major

        if [ "${{ inputs.isTerraformModule }}" = "true" ]; then
          sed -i "s/\("technical:module:version"\).*/\1: \"${{ steps.gitversion.outputs.major }}\"/" 01-locals.tf
          sed -i "s/\(terraform-aws-.*?ref=\).*/\1v${{ steps.gitversion.outputs.major }}\"/" README.md
          sed -i "s/\(terraform-aws-.*?ref=\).*/\1v${{ steps.gitversion.outputs.major }}\"/" .terraform-docs.yml
        fi

        git add 01-locals.tf README.md .terraform-docs.yml || true
        git commit -m "chore: bump module version to v${{ steps.gitversion.outputs.major }}" || echo "No changes to commit"

        git tag "v${{ steps.gitversion.outputs.major }}"
        git push origin "v${{ steps.gitversion.outputs.major }}"

    - name: Push Major.Minor Version Tag
      if: ${{ inputs.pushMajorMinorVersionTag == 'true' }}
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -d "v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}" || true
        git push origin ":refs/tags/v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}" || true
        
        git checkout -b tmp-release-major-minor

        if [ "${{ inputs.isTerraformModule }}" = "true" ]; then
          sed -i "s/\("technical:module:version"\).*/\1: \"${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}\"/" 01-locals.tf
          sed -i "s/\(terraform-aws-.*?ref=\).*/\1v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}\"/" README.md
          sed -i "s/\(terraform-aws-.*?ref=\).*/\1v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}\"/" .terraform-docs.yml
        fi

        git add 01-locals.tf README.md .terraform-docs.yml || true
        git commit -m "chore: bump module version to v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}" || echo "No changes to commit"

        git tag "v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}"
        git push origin "v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}"
    
    - name: Push Major.Minor.Patch Version Tag
      if: ${{ inputs.pushMajorMinorPatchVersionTag == 'true' }}
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git checkout -b tmp-release-major-minor-patch

        if [ "${{ inputs.isTerraformModule }}" = "true" ]; then
          sed -i "s/\("technical:module:version"\).*/\1: \"${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}\"/" 01-locals.tf
          sed -i "s/\(terraform-aws-.*?ref=\).*/\1v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}\"/" README.md
          sed -i "s/\(terraform-aws-.*?ref=\).*/\1v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}\"/" .terraform-docs.yml
        fi

        git add 01-locals.tf README.md .terraform-docs.yml || true
        git commit -m "chore: bump module version to v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}" || echo "No changes to commit"

        git tag "v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}"
        git push origin "v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}"

    - name: Set outputs
      shell: bash
      run: |
        echo "gitversion-fullsemver=${{ steps.gitversion.outputs.fullSemVer }}" >> $GITHUB_OUTPUT
        echo "gitversion-sha=${{ steps.gitversion.outputs.sha }}" >> $GITHUB_OUTPUT
