name: 'GitVersion Action'
description: 'This GitHub Action extracts version information using GitVersion and optionally updates Terraform module files and generates changelogs using git-cliff.'

inputs:
  useGitVersionDefaultConfig:
    description: 'Whether to use the default GitVersion configuration'
    required: false
    default: 'true'

  gitVersionConfigFilePath:
    description: 'Path to a custom GitVersion configuration file'
    required: false
    default: 'gitversion.yml'
  
  useCliffDefaultConfig:
    description: 'Whether to use the default git-cliff configuration'
    required: false
    default: 'true'

  cliffConfigFilePath:
    description: 'Path to a custom git-cliff configuration file'
    required: false
    default: 'cliff.toml'

  isTerraformModule:
    description: 'Whether the repository is a Terraform module'
    required: false
    default: 'false'

outputs:
  majorVersion:
    description: 'Major version number'
    value: ${{ steps.gitversion.outputs.major }}

  minorVersion:
    description: 'Minor version number'
    value: ${{ steps.gitversion.outputs.minor }}

  patchVersion:
    description: 'Patch version number'
    value: ${{ steps.gitversion.outputs.patch }}

  majorMinorVersion:
    description: 'Major.Minor version'
    value: ${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}
  
  majorMinorPatchVersion:
    description: 'Major.Minor.Patch version'
    value: ${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}.${{ steps.gitversion.outputs.patch }}

runs:
  using: 'composite'
  steps:
    # - name: Install Terraform
    #   if: ${{ inputs.isTerraformModule == 'true' }}
    #   uses: hashicorp/setup-terraform@v3

    # - name: Terraform fmt
    #   if: ${{ inputs.isTerraformModule == 'true' }}
    #   shell: bash
    #   run: terraform fmt -check
    #   continue-on-error: false

    - name: Create default GitVersion config
      if: ${{ inputs.useGitVersionDefaultConfig == 'true' }}
      shell: bash
      run: |
        echo "==> Creating default GitVersion configuration file (gitversion.yml)..."
        cat > gitversion.yml << 'EOF'
        workflow: GitHubFlow/v1
        tag-prefix: '[vV]'
        major-version-bump-message: '(BREAKING CHANGE|^.+!:)'
        minor-version-bump-message: '^feat(\([^)]+\))?:\s'
        patch-version-bump-message: '^(fix|perf|refactor|revert|chore|docs|style|test|ci)(\([^)]+\))?:\s'
        #patch-version-bump-message: '^(fix|perf|refactor|revert)(\([^)]+\))?:\s'
        #no-bump-message: '^(chore|docs|style|test|ci)(\([^)]+\))?:\s'
        commit-message-incrementing: Enabled
        strategies:
          - MergeMessage
          - TaggedCommit
          - TrackReleaseBranches
          - VersionInBranchName
        branches:
          main:
            mode: ContinuousDeployment
            increment: Patch
            regex: ^master$|^main$
            is-main-branch: true
          release:
            mode: ContinuousDeployment
            increment: Minor
            regex: ^release/(?<BranchName>[0-9]+\.[0-9]+\.[0-9]+)$
            is-release-branch: true
          develop:
            mode: ContinuousDelivery
            increment: Patch
            regex: ^dev(elop)?(ment)?$
        commit-date-format: ddMMyyyy
        assembly-versioning-scheme: MajorMinorPatch
        assembly-informational-format: '{SemVer}'
        EOF
        echo "Default gitversion.yml created."

    - name: Create default cliff.toml config
      if: ${{ inputs.useCliffDefaultConfig == 'true' }}
      shell: bash
      run: |
        echo "==> Creating default Cliff configuration file (cliff.toml)..."
        cat > cliff.toml << 'EOF'
        [changelog]
        # Global template
        header = """# Change Log

        All notable changes to this project will be documented in this file.

        """

        # Template for each version
        body = """
        ## [CHANGEME](${{ github.server_url }}/${{ github.repository }}/compare/{{ previous.version }}...CHANGEME) ({{ now() | date(format="%Y-%m-%d") }})

        {% for commit in commits %}
        {% if not commit.message | contains(pat="bump") %}
        - {{ commit.message | split(pat="\n") | first | upper_first }}
        {% endif %}
        {% endfor %}

        """

        [git]
        tag_filter_pattern = "^v[0-9]{1,}\\.[0-9]{1,}\\.[0-9]{1,}$"

        footer = ""
        trim = true

        EOF
        echo "Default cliff.toml created."

    - name: Set up git-cliff
      uses: kenji-miyake/setup-git-cliff@v1
      
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v4
      with:
        versionSpec: '6.4.x'

    - name: Execute GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v4
      with:
        configFilePath: ${{ inputs.gitVersionConfigFilePath }}

    - name: Export version variables
      shell: bash
      run: |
        echo "MAJOR_VERSION=${{ steps.gitversion.outputs.major }}" >> $GITHUB_ENV
        echo "MINOR_VERSION=${{ steps.gitversion.outputs.minor }}" >> $GITHUB_ENV
        echo "PATCH_VERSION=${{ steps.gitversion.outputs.patch }}" >> $GITHUB_ENV

    - name: Configure Git
      shell: bash
      run: |
        echo "==> Configuring Git user..."
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Push Version Tags and Update Terraform Module Files
      if : ${{ inputs.isTerraformModule == 'true' }}
      shell: bash
      run: |    
        update_version() {
          sed -i "s/\(\"technical:module:version\"\).*/\1 : \"$1\"/" 01-locals.tf
          sed -i "s/\(terraform-aws-.*?ref=\).*/\1v$1\"/" README.md
          sed -i "s/\(terraform-aws-.*?ref=\).*/\1v$1\"/" .terraform-docs.yml

          git add 01-locals.tf README.md .terraform-docs.yml CHANGELOG.md || true
          git commit -m "chore: bump version to v$1" || echo "No changes to commit."
          
          git tag "v$1"
          git push origin "v$1"
        }

        # Delete existing tags if they exist
        git tag -d v${{ env.MAJOR_VERSION }} v${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }} || true
        git push origin ":refs/tags/v${{ env.MAJOR_VERSION }}" ":refs/tags/v${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}" || true

        # Generate changelog
        git cliff --config ${{ inputs.cliffConfigFilePath }} -u --prepend CHANGELOG.md
        sed -i "s/CHANGEME/${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.PATCH_VERSION }}/g" CHANGELOG.md

        update_version ${{ env.MAJOR_VERSION }}
        update_version ${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}
        update_version ${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.PATCH_VERSION }}

        git push origin $(git rev-parse --abbrev-ref HEAD)
